In [4]:
#data.shape = (128,128)
import torch 
import torch.nn 
import numpy as np 
data = torch.rand(size = (128,128),dtype = torch.float32)
data 

tensor([[0.2704, 0.3656, 0.8267,  ..., 0.9263, 0.7322, 0.9561],
        [0.5090, 0.4851, 0.7760,  ..., 0.2043, 0.8134, 0.4060],
        [0.9290, 0.0254, 0.5643,  ..., 0.3020, 0.4962, 0.9671],
        ...,
        [0.1274, 0.3173, 0.1526,  ..., 0.5124, 0.5151, 0.3635],
        [0.3985, 0.6722, 0.8029,  ..., 0.3269, 0.6458, 0.7308],
        [0.3939, 0.9708, 0.0229,  ..., 0.9821, 0.8292, 0.6163]])

In [10]:
print (data.shape)
i = 0 
kernel =2 
j=0  
print ( data[i:i+2,j:j+2 ])
data_flatten = torch.flatten(data[i:i+kernel,j:j+kernel])
print(data_flatten) 
ex = data_flatten

torch.Size([128, 128])
tensor([[0.2704, 0.3656],
        [0.5090, 0.4851]])
tensor([0.2704, 0.3656, 0.5090, 0.4851])


In [ ]:
def scale_data ( data : torch.tensor , new_min : int , new_max : int )->  torch.tensor : 
    t_min = data.min() 
    t_max = data.max() 
    scaled_data = new_min + (data-t_min)*(new_max - new_min)/(t_max -t_min)
    return scaled_data *np.pi

scaled_data = scale_data(ex, -1 ,1 )
print ( scaled_data ) 

tensor([-1.0000, -0.2019,  1.0000,  0.7993])


In [ ]:
def vqc_cell (data : torch.tensor ) : 
    

In [ ]:
def conv_qt ( data :torch.tensor, stride : int , padding : int , kernel : int  )->torch.tensor : 
    data = data*np.pi
    W,H = data.shape 
    for i in range(0,W-kernel+1, stride ) : 
        for j in range (0,H-kernel+1,stride):
            data_flatten = torch.flatten(data[i:i+kernel,j:j+kernel])
            scaled_data = scale_data(data_flatten, -1,1 )
            


    return 
